require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WeatherReportsController do

  # This should return the minimal set of attributes required to create a valid
  # WeatherReport. As you add validations to WeatherReport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "time_received" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WeatherReportsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all weather_reports as @weather_reports" do
      weather_report = WeatherReport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:weather_reports).should eq([weather_report])
    end
  end

  describe "GET show" do
    it "assigns the requested weather_report as @weather_report" do
      weather_report = WeatherReport.create! valid_attributes
      get :show, {:id => weather_report.to_param}, valid_session
      assigns(:weather_report).should eq(weather_report)
    end
  end

  describe "GET new" do
    it "assigns a new weather_report as @weather_report" do
      get :new, {}, valid_session
      assigns(:weather_report).should be_a_new(WeatherReport)
    end
  end

  describe "GET edit" do
    it "assigns the requested weather_report as @weather_report" do
      weather_report = WeatherReport.create! valid_attributes
      get :edit, {:id => weather_report.to_param}, valid_session
      assigns(:weather_report).should eq(weather_report)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WeatherReport" do
        expect {
          post :create, {:weather_report => valid_attributes}, valid_session
        }.to change(WeatherReport, :count).by(1)
      end

      it "assigns a newly created weather_report as @weather_report" do
        post :create, {:weather_report => valid_attributes}, valid_session
        assigns(:weather_report).should be_a(WeatherReport)
        assigns(:weather_report).should be_persisted
      end

      it "redirects to the created weather_report" do
        post :create, {:weather_report => valid_attributes}, valid_session
        response.should redirect_to(WeatherReport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved weather_report as @weather_report" do
        # Trigger the behavior that occurs when invalid params are submitted
        WeatherReport.any_instance.stub(:save).and_return(false)
        post :create, {:weather_report => { "time_received" => "invalid value" }}, valid_session
        assigns(:weather_report).should be_a_new(WeatherReport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WeatherReport.any_instance.stub(:save).and_return(false)
        post :create, {:weather_report => { "time_received" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested weather_report" do
        weather_report = WeatherReport.create! valid_attributes
        # Assuming there are no other weather_reports in the database, this
        # specifies that the WeatherReport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WeatherReport.any_instance.should_receive(:update).with({ "time_received" => "1" })
        put :update, {:id => weather_report.to_param, :weather_report => { "time_received" => "1" }}, valid_session
      end

      it "assigns the requested weather_report as @weather_report" do
        weather_report = WeatherReport.create! valid_attributes
        put :update, {:id => weather_report.to_param, :weather_report => valid_attributes}, valid_session
        assigns(:weather_report).should eq(weather_report)
      end

      it "redirects to the weather_report" do
        weather_report = WeatherReport.create! valid_attributes
        put :update, {:id => weather_report.to_param, :weather_report => valid_attributes}, valid_session
        response.should redirect_to(weather_report)
      end
    end

    describe "with invalid params" do
      it "assigns the weather_report as @weather_report" do
        weather_report = WeatherReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WeatherReport.any_instance.stub(:save).and_return(false)
        put :update, {:id => weather_report.to_param, :weather_report => { "time_received" => "invalid value" }}, valid_session
        assigns(:weather_report).should eq(weather_report)
      end

      it "re-renders the 'edit' template" do
        weather_report = WeatherReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WeatherReport.any_instance.stub(:save).and_return(false)
        put :update, {:id => weather_report.to_param, :weather_report => { "time_received" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested weather_report" do
      weather_report = WeatherReport.create! valid_attributes
      expect {
        delete :destroy, {:id => weather_report.to_param}, valid_session
      }.to change(WeatherReport, :count).by(-1)
    end

    it "redirects to the weather_reports list" do
      weather_report = WeatherReport.create! valid_attributes
      delete :destroy, {:id => weather_report.to_param}, valid_session
      response.should redirect_to(weather_reports_url)
    end
  end

end
